bipedal-locomotion-controllers: BipedalLocomotionControllers::ParametersHandler::YarpImplementation Class Reference
BipedalLocomotionControllers::ParametersHandler::YarpImplementation Class Reference
Parameters handler interface.
#include <BipedalLocomotionControllers/ParametersHandler/YarpImplementation.h>
Public Types
using unique_ptr = std::unique_ptr< IParametersHandler< YarpImplementation > >
Public Member Functions
YarpImplementation (const yarp::os::Searchable &searchable)
Constructor.
YarpImplementation ()=default
Constructor.
template<typename T >
bool getParameter (const std::string &parameterName, T &parameter) const
Get a parameter from the handler.
template<typename T >
void setParameter (const std::string &parameterName, const T &parameter)
Set a parameter in the handler.
std::unique_ptr< IParametersHandler< YarpImplementation > > getGroup (const std::string &name) const
Get a Group from the handler.
std::string toString () const
Return a standard text representation of the content of the object.
~YarpImplementation ()=default
Destructor.
Detailed Description
Parameters handler interface.
Yarp Implementation (Curiously recurring template pattern)
Definition at line 37 of file YarpImplementation.h.
Constructor & Destructor Documentation
YarpImplementation()
YarpImplementation::YarpImplementation (const yarp::os::Searchable & searchable)
Constructor.
Parameters
searchable reference to a searchable object. The object is copied inside the Handler
Definition at line 14 of file YarpImplementation.cpp.
References yarp::os::Property::fromString(), and yarp::os::Searchable::toString().
Member Function Documentation
getGroup()
std::unique_ptr< IParametersHandler< YarpImplementation > > YarpImplementation::getGroup (const std::string & name) const
Get a Group from the handler.
Parameters
name name of the group
Returns
A pointer to IParametersHandler, If the group is not found a new empty object is created and returned
Definition at line 20 of file YarpImplementation.cpp.
References yarp::os::Property::findGroup().
getParameter()
template<typename T > bool BipedalLocomotionControllers::ParametersHandler::YarpImplementation::getParameter (const std::string & parameterName, T & parameter) const
Get a parameter from the handler.
Parameters
parameterName name of the parameter
parameter parameter
Template Parameters
T type of the parameter
Returns
true/false in case of success/failure
Definition at line 18 of file YarpImplementation.tpp.
References BipedalLocomotionControllers::YarpUtilities::getElementFromSearchable(), and BipedalLocomotionControllers::YarpUtilities::getVectorFromSearchable().
setParameter()
template<typename T > void BipedalLocomotionControllers::ParametersHandler::YarpImplementation::setParameter (const std::string & parameterName, const T & parameter)
Set a parameter in the handler.
Parameters
parameterName name of the parameter
parameter parameter
Template Parameters
T type of the parameter
Returns
true/false in case of success/failure
Definition at line 29 of file YarpImplementation.tpp.
References yarp::os::Bottle::add(), yarp::os::Value::asList(), and yarp::os::Property::put().
toString()
std::string YarpImplementation::toString () const
Return a standard text representation of the content of the object.
Returns
a string containing the standard text representation of the content of the object.
Definition at line 29 of file YarpImplementation.cpp.
References yarp::os::Property::toString().
The documentation for this class was generated from the following files:
ParametersHandler/YarpImplementation/include/BipedalLocomotionControllers/ParametersHandler/YarpImplementation.h
ParametersHandler/YarpImplementation/include/BipedalLocomotionControllers/ParametersHandler/YarpImplementation.tpp
ParametersHandler/YarpImplementation/src/YarpImplementation.cpp